name: Check & fix styling

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
<<<<<<< HEAD
<<<<<<< HEAD
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes
=======
          args: --config=.php_cs.dist.php --allow-risky=yes
>>>>>>> 900ef25 (up)
=======
          args: --config=.php_cs.dist.php --allow-risky=yes
>>>>>>> 145ec6b (.)

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Check & fix styling
